// Datos de proyectos - fuente única de verdad para cards y página de detalle.
// Las galerías completas viven en images/projects/{slug}/gallery/ (NN.webp = versión liviana,
// NN_xl.webp = 2800px para el visor en pantalla completa). galleryCount indica cuántas hay.
// Cada proyecto tiene un bloque `en` con la traducción de los campos de texto para el toggle ES/EN.

const projects = [
  {
    id: 12,
    slug: 'parque-thays',
    title: 'Renovación caniles',
    titleAccent: 'Renovación caniles',
    titleRest: 'Parque Thays, CABA',
    category: 'urbano',
    academic: false,
    role: 'Proyecto y dirección de obra',
    tags: ['Proyecto y dirección de obra'],
    location: 'Recoleta, CABA',
    year: '2026',
    surface: '7.300 m²',
    quote: 'Recoleta es uno de los barrios con más perros por habitante de la ciudad. Sin embargo, tener un espacio adecuado para ellos no siempre fue una realidad.',
    description: [
      'La intervención se ubica en el Parque Thays, un espacio público de escala metropolitana de aproximadamente 58.900 m², delimitado por Brigadier General Juan Facundo Quiroga, Julio Víctor González, Av. Callao y Av. del Libertador. El sector contaba con un canil informal de baja altura, sin rejas reglamentarias, por donde los perros se escapaban. La concentración de todos los usuarios en un único espacio generaba además conflictos constantes entre perros y paseadores.',
      'La intervención consistió en ampliar y formalizar el sector, construyendo un nuevo muro perimetral con rejas reglamentarias, alcanzando una superficie total de 7.300 m². La gran novedad del proyecto fue la subdivisión del espacio en 12 sectores diferenciados, una solución poco explorada en Argentina pero ya implementada en otros países, que permite separar usos y evitar conflictos. Cada subdivisión incorporó dobles portones, diseñados para desembocar en dos caniles simultáneos, permitiendo generar un canil doble en caso de mayor demanda. De esta manera, cada sector quedó con más de 600 m², el tamaño promedio de un canil estándar en cualquier otra plaza de la ciudad.',
      'Se incorporaron tres accesos desde la calle Facundo Quiroga, dos de los cuales desembocan directamente en los caniles, pensando en los usuarios que llegan con sus perros en vehículo. A su vez, algunas rejas fueron adaptadas para acompañar las raíces de los árboles existentes, respetando la vegetación del lugar y sin afectar el entorno.',
    ],
    description_short: 'Puesta en valor y ampliación de canil, en Parque Thays (proyecto y dirección de obra). Proyecto real (2026).',
    behanceUrl: 'https://www.behance.net/gallery/247725239/Renovacion-caniles-Parque-Thays-%28CABA%29',
    image: 'images/projects/parque-thays/preview.jpg',
    imageAlt: 'Caniles Parque Thays',
    galleryCount: 12,
    heroIndex: 4,
    en: {
      title: 'Dog park renovation',
      titleAccent: 'Dog park renovation',
      titleRest: 'Parque Thays, Buenos Aires',
      role: 'Design & site management',
      tags: ['Design & site management'],
      location: 'Recoleta, Buenos Aires',
      surface: '7,300 m²',
      quote: "Recoleta is one of the neighborhoods with the most dogs per capita in the city - yet having a proper space for them wasn't always a reality.",
      description: [
        'The intervention is located in Parque Thays, a metropolitan-scale public space of approximately 58,900 m², bounded by Brigadier General Juan Facundo Quiroga, Julio Víctor González, Av. Callao and Av. del Libertador. The site had an informal, low dog park with no code-compliant fencing, which let dogs escape. Concentrating every user in a single space also caused constant conflicts between dogs and dog walkers.',
        "The intervention expanded and formalized the area, building a new perimeter wall with code-compliant fencing and reaching a total surface of 7,300 m². The project's biggest innovation was subdividing the space into 12 differentiated sectors - a solution rarely explored in Argentina but already implemented elsewhere - allowing uses to be separated and conflicts avoided. Each subdivision incorporated double gates designed to open onto two simultaneous dog runs, making it possible to combine them into a larger run at peak demand. This left each sector with more than 600 m², the average size of a standard dog run elsewhere in the city.",
        'Three accesses were added from Facundo Quiroga street, two of which lead directly into the dog runs, designed for users arriving with their dogs by car. Some fences were also adapted to accommodate the roots of existing trees, respecting the site’s vegetation without affecting its surroundings.',
      ],
      description_short: 'Restoration and expansion of a dog park in Parque Thays (design and site management). Built project (2026).',
      imageAlt: 'Parque Thays dog runs',
    },
  },
  {
    id: 11,
    slug: 'plaza-ruben-dario',
    title: 'Estación deportiva',
    titleAccent: 'Estación deportiva',
    titleRest: 'Plaza Rubén Darío, CABA',
    category: 'urbano',
    academic: false,
    role: 'Proyecto y dirección de obra',
    tags: ['Proyecto y dirección de obra'],
    location: 'Recoleta, CABA',
    year: '2026',
    surface: '1.000 m²',
    quote: 'Diseñar un espacio orientado a adultos mayores no es adaptar lo que ya existe, sino pensar desde cero en lo que realmente necesitan.',
    description: [
      'La intervención se ubica en Plaza Rubén Darío, uno de los espacios verdes más extensos de la ciudad, con aproximadamente 63.000 m² delimitados por Av. Presidente Figueroa Alcorta, Av. del Libertador, Av. Pueyrredón y la calle Austria. El sector intervenido contaba con postas deportivas orientadas mayormente a un público joven, sin contemplar las necesidades específicas de los adultos mayores.',
      'El proyecto consistió en generar un anexo al sector deportivo existente, en estrecha relación con la Estación Saludable de la plaza, a la que ya concurrían habitualmente vecinos mayores a realizar actividad física. Sobre un solado de caucho que unifica visualmente el nuevo sector con el existente y aporta seguridad ante posibles caídas, se incorporaron postas deportivas adaptadas para adultos mayores, junto a mobiliario accesible y funcional para acompañar las pausas y fomentar el encuentro social.',
      'Lo más novedoso de la intervención fue la incorporación de lonas tensadas para generar sombra sobre el sector, una solución fundamental en una zona sin cobertura arbórea donde se realiza actividad física.',
    ],
    description_short: 'Estación deportiva para adultos mayores en Plaza Rubén Darío (proyecto y dirección de obra). Proyecto real (2026).',
    behanceUrl: 'https://www.behance.net/gallery/247724323/Estacion-deportiva-Rubn-Dario-%28CABA%29',
    image: 'images/projects/plaza-ruben-dario/preview.jpg',
    imageAlt: 'Estación deportiva Plaza Rubén Darío',
    galleryCount: 12,
    heroIndex: 3,
    en: {
      title: 'Sports station',
      titleAccent: 'Sports station',
      titleRest: 'Plaza Rubén Darío, Buenos Aires',
      role: 'Design & site management',
      tags: ['Design & site management'],
      location: 'Recoleta, Buenos Aires',
      surface: '1,000 m²',
      quote: "Designing a space for older adults isn't about adapting what already exists - it's about rethinking, from scratch, what they actually need.",
      description: [
        "The intervention is located in Plaza Rubén Darío, one of the city's largest green spaces, with roughly 63,000 m² bounded by Av. Presidente Figueroa Alcorta, Av. del Libertador, Av. Pueyrredón and Austria street. The intervened sector had sports stations aimed mostly at a younger audience, without addressing the specific needs of older adults.",
        "The project added an annex to the existing sports sector, closely related to the plaza's Estación Saludable outdoor fitness station, which older neighbors already used regularly for physical activity. On a rubber surface that visually unifies the new sector with the existing one and reduces the risk of falls, adapted sports stations for older adults were installed, along with accessible, functional furniture to support rest breaks and encourage social interaction.",
        'The most novel part of the intervention was adding tensioned canvas sails to provide shade over the sector - an essential solution in an area with no tree cover where physical activity takes place.',
      ],
      description_short: 'Sports station for older adults in Plaza Rubén Darío (design and site management). Built project (2026).',
      imageAlt: 'Plaza Rubén Darío sports station',
    },
  },
  {
    id: 10,
    slug: 'plaza-borges',
    title: 'Puesta en valor',
    titleAccent: 'Puesta en valor',
    titleRest: 'Plaza Borges, CABA',
    category: 'urbano',
    academic: false,
    role: 'Proyecto y dirección de obra',
    tags: ['Proyecto y dirección de obra'],
    location: 'Recoleta, CABA',
    year: '2025 – 2026',
    surface: '1.250 m²',
    quote: 'Hay espacios que llevan un nombre con mucho peso, pero su diseño e infraestructura no terminan de acompañarlo.',
    description: [
      'La intervención se ubica en Plaza Jorge Luis Borges, Recoleta, un espacio público de aproximadamente 2.000 m² ubicado en la esquina de Av. Las Heras y Austria, en las inmediaciones de la Biblioteca Nacional Mariano Moreno y el Museo del Libro y de la Lengua. A pesar de su entorno cultural privilegiado, la plaza carecía de identidad temática, accesibilidad y mobiliario adecuado.',
      'La propuesta giró en torno a la incorporación de un laberinto de canteros en homenaje a la obra de Borges, construido en pórfido, el mismo material que ya tenía la plaza, para respetar y continuar con su lenguaje existente. Este trazado complejizó el recorrido e invitó a la permanencia. Para garantizar la accesibilidad al sector elevado, se incorporó una rampa que conecta los distintos niveles de la plaza.',
      'El recorrido se complementó con la restauración de una fuente que llevaba años inactiva y la incorporación de nuevo mobiliario de hormigón, pensado para quienes se acercan a descansar o contemplar la vista hacia la Biblioteca Nacional. Por último, se intervino la medianera con un mural temático vinculado a Borges, sumando una capa simbólica y visual que refuerza la identidad del conjunto.',
    ],
    description_short: 'Puesta en valor cultural en Plaza Jorge L. Borges (proyecto y dirección de obra). Proyecto real (2025/2026).',
    behanceUrl: 'https://www.behance.net/gallery/247723131/Puesta-en-valor-Plaza-Jorge-L-Borges-%28CABA%29',
    image: 'images/projects/plaza-borges/gallery/14.webp',
    imageAlt: 'Puesta en valor Plaza Borges',
    galleryCount: 13,
    heroImage: 'images/projects/plaza-borges/gallery/14.webp',
    en: {
      title: 'Public space restoration',
      titleAccent: 'Public space restoration',
      titleRest: 'Plaza Borges, Buenos Aires',
      role: 'Design & site management',
      tags: ['Design & site management'],
      location: 'Recoleta, Buenos Aires',
      surface: '1,250 m²',
      quote: "Some spaces carry a name with real weight, but their design and infrastructure don't quite live up to it.",
      description: [
        "The intervention is located in Plaza Jorge Luis Borges, Recoleta, a public space of approximately 2,000 m² at the corner of Av. Las Heras and Austria, near the Biblioteca Nacional Mariano Moreno and the Museo del Libro y de la Lengua. Despite its privileged cultural surroundings, the plaza lacked a thematic identity, accessibility and adequate furniture.",
        "The proposal centers on a labyrinth of planters paying tribute to Borges' work, built in porphyry - the same material the plaza already had - to respect and continue its existing language. This layout added complexity to the route and invited people to linger. To guarantee accessibility to the raised sector, a ramp connecting the plaza's different levels was added.",
        'The route was complemented by restoring a fountain that had been out of service for years and adding new concrete furniture, designed for those stopping to rest or take in the view toward the Biblioteca Nacional. Finally, the party wall was intervened with a Borges-themed mural, adding a symbolic and visual layer that reinforces the identity of the whole.',
      ],
      description_short: 'Cultural restoration of Plaza Jorge L. Borges (design and site management). Built project (2025/2026).',
      imageAlt: 'Plaza Borges restoration',
    },
  },
  {
    id: 9,
    slug: 'plaza-houssay',
    title: 'Sector deportivo',
    titleAccent: 'Sector deportivo',
    titleRest: 'Plaza Houssay, CABA',
    category: 'urbano',
    academic: false,
    role: 'Proyecto y dirección de obra',
    tags: ['Proyecto y dirección de obra'],
    location: 'Recoleta, CABA',
    year: '2025',
    surface: '2.000 m²',
    quote: 'Un espacio público deteriorado no es solo un problema estético, sino una deuda con la gente que lo usa todos los días.',
    description: [
      'La intervención se ubica en Plaza Houssay, Recoleta, un espacio público con fuerte impronta universitaria, rodeado por facultades y el complejo hospitalario. El sector intervenido presentaba un solado quebrado y una infraestructura que no respondía a la intensidad de uso del lugar.',
      'El proyecto incorporó un área deportiva mixta compuesta por canchas de fútbol, básquet y vóley, junto a dos canchas multifuncionales de césped sintético vinculadas a la Estación Saludable existente. El diseño partió de observar lo que ya ocurría en la plaza de manera informal: el fútbol y el básquet se practicaban ahí desde hacía años, sobre un solado que ya no acompañaba. La propuesta buscó darle forma, soporte y calidad a esas dinámicas.',
      'Se reemplazó el deck de madera deteriorado por una rampa de hormigón, mejorando la accesibilidad del sector. Las antiguas gradas fueron sustituidas por canteros con vegetación, sumando superficie verde y ordenando los usos del espacio. Por último, se incorporó un área de estar con mobiliario pensado para el uso estudiantil y vecinal.',
    ],
    description_short: 'Intervención sector deportivo ubicado en Plaza Houssay (proyecto y dirección de obra). Proyecto real (2025).',
    behanceUrl: 'https://www.behance.net/gallery/247721249/Sector-deportivo-Plaza-Houssay-%28CABA%29',
    image: 'images/projects/plaza-houssay/preview.jpg',
    imageAlt: 'Sector deportivo Plaza Houssay',
    galleryCount: 14,
    heroIndex: 4,
    en: {
      title: 'Sports sector',
      titleAccent: 'Sports sector',
      titleRest: 'Plaza Houssay, Buenos Aires',
      role: 'Design & site management',
      tags: ['Design & site management'],
      location: 'Recoleta, Buenos Aires',
      surface: '2,000 m²',
      quote: "A deteriorated public space isn't just an aesthetic problem - it's a debt owed to the people who use it every day.",
      description: [
        "The intervention is located in Plaza Houssay, Recoleta, a public space with a strong university character, surrounded by university faculties and the hospital complex. The intervened sector had cracked paving and infrastructure that no longer matched the site's intensity of use.",
        "The project added a mixed sports area with soccer, basketball and volleyball courts, together with two multi-purpose synthetic turf courts linked to the existing Estación Saludable. The design started from observing what already happened informally in the plaza: soccer and basketball had been played there for years, on paving that could no longer keep up. The proposal set out to give those dynamics shape, support and quality.",
        'The deteriorated wooden deck was replaced with a concrete ramp, improving the accessibility of the sector. The old bleachers were replaced with planters, adding green surface and organizing the uses of the space. Finally, a seating area with furniture designed for student and neighborhood use was added.',
      ],
      description_short: 'Sports sector intervention in Plaza Houssay (design and site management). Built project (2025).',
      imageAlt: 'Plaza Houssay sports sector',
    },
  },
  {
    id: 8,
    slug: 'proyecto-centro-cientifico',
    title: 'Centro científico',
    titleAccent: 'Centro científico',
    titleRest: 'Bahía Blanca, Bs. As.',
    category: 'institucional',
    academic: true,
    role: 'Proyecto universitario',
    tags: ['Proyecto universitario'],
    location: 'Bahía Blanca, Buenos Aires',
    year: '2025',
    surface: '13.300 m²',
    quote: 'La arquitectura se posa sobre el marisma como un dispositivo de lectura, estudio y convivencia con un territorio en permanente transformación.',
    description: [
      'Ubicado en el estuario de Bahía Blanca, el proyecto se implanta en un paisaje dominado por el marisma, un ecosistema dinámico e inestable donde el límite entre agua y tierra se redefine constantemente. En este contexto, la propuesta concibe la arquitectura no como un objeto autónomo, sino como una herramienta capaz de acompañar y revelar las lógicas del territorio.',
      'La estrategia de implantación se apoya en la identificación de micropaisajes, entre los cuales se distinguen: pequeños cauces, acumulaciones de sedimentos y vegetación dispersa; y que reproducen la morfología del marisma a menor escala y permiten anclar el edificio sin negar su carácter mutable. Esta condición se refuerza mediante la relación directa con uno de los canales de navegación del estuario.',
      'Los programas públicos de mayor escala se desarrollan en planta baja sobre cuatro tablestacados estructurales de igual dimensión, que rigidizan el suelo y alojan el hall, auditorio, biblioteca y cafetería. Entre ellos se generan vacíos que permiten el ingreso de vegetación autóctona, diluyendo el límite entre lo construido y el paisaje. Cada tablestacado construye una atmósfera distinta, desde lo más contenido hasta lo más permeable, respondiendo al carácter específico de cada programa.',
      'Los programas privados, que responden a laboratorios y dormitorios para investigadores, se elevan en un anillo colgante suspendido mediante tensores metálicos, liberando la planta baja de apoyos y garantizando visuales continuas y mayor privacidad.',
      'La estructura metálica se resuelve con perfilería liviana y losas de steel deck, y cuenta con tratamiento de galvanizado en caliente para resistir las condiciones de humedad y salinidad del estuario. Las cubiertas inclinadas permiten la recolección y reutilización de agua de lluvia para cultivos experimentales asociados al edificio.',
    ],
    description_short: 'Centro científico ubicado en Bahía Blanca (proyecto propio). Proyecto universitario para Proyecto Arquitectónico (2025).',
    behanceUrl: 'https://www.behance.net/gallery/240788631/Centro-de-formacion-cientifica-Bahia-Blanca',
    image: 'images/projects/proyecto-centro-cientifico/gallery/hero-02.webp',
    imageAlt: 'Centro de formación científica',
    galleryCount: 22,
    heroImage: 'images/projects/proyecto-centro-cientifico/gallery/hero-02.webp',
    en: {
      title: 'Science center',
      titleAccent: 'Science center',
      titleRest: 'Bahía Blanca, Argentina',
      role: 'University project',
      tags: ['University project'],
      location: 'Bahía Blanca, Buenos Aires',
      surface: '13,300 m²',
      quote: "The architecture rests on the salt marsh as a device for reading, studying and coexisting with a territory in constant transformation.",
      description: [
        "Located in the Bahía Blanca estuary, the project sits within a landscape dominated by the marisma, a dynamic, unstable ecosystem where the boundary between water and land is constantly redefined. In this context, the proposal conceives architecture not as an autonomous object, but as a tool capable of accompanying and revealing the territory's own logic.",
        "The siting strategy relies on identifying micro-landscapes - small channels, sediment build-up and scattered vegetation - that reproduce the marisma's morphology at a smaller scale and let the building anchor itself without denying its shifting character. This condition is reinforced through a direct relationship with one of the estuary's navigation channels.",
        'The larger-scale public programs are laid out on the ground floor over four structural sheet-pile foundations of equal size, which stiffen the ground and house the lobby, auditorium, library and cafeteria. Voids between them let native vegetation in, blurring the line between what is built and the landscape. Each foundation builds a distinct atmosphere, from the most enclosed to the most permeable, responding to the specific character of each program.',
        'The private programs - laboratories and dormitories for researchers - rise in a suspended ring hung from metal tensors, freeing the ground floor of supports and guaranteeing continuous views and greater privacy.',
        "The steel structure is resolved with lightweight framing and steel deck slabs, with hot-dip galvanizing to withstand the estuary's humidity and salinity. The sloped roofs allow rainwater to be collected and reused for the experimental crops associated with the building.",
      ],
      description_short: 'Science center located in Bahía Blanca (own project). University project for Proyecto Arquitectónico (2025).',
      imageAlt: 'Science education center',
    },
  },
  {
    id: 7,
    slug: 'proyecto-parque-agroproductivo',
    title: 'Parque agroproductivo',
    titleAccent: 'Parque agroproductivo',
    titleRest: 'Viedma, Bs. As.',
    category: 'urbano',
    academic: true,
    role: 'Proyecto universitario',
    tags: ['Proyecto universitario'],
    location: 'Viedma, Buenos Aires',
    year: '2025',
    surface: '135 km²',
    quote: 'El proyecto transforma una condición de vulnerabilidad hídrica en una infraestructura productiva capaz de organizar el territorio y construir paisaje.',
    description: [
      'Ubicado en la llanura aluvial de Viedma, el proyecto surge como respuesta a las crecidas del Río Negro, que afectan de manera recurrente a la ciudad debido a su baja cota. Mientras Carmen de Patagones se desarrolla sobre una barranca natural que la protege de inundaciones, Viedma se asienta sobre una llanura aluvial vulnerable, donde el agua actúa simultáneamente como recurso productivo y como amenaza latente.',
      'En este contexto, la propuesta toma al agua como punto de partida y plantea un sistema de canales capaz de regular y derivar parte del caudal del río. De este modo, el control hídrico, la producción agrícola y la mitigación de crecidas se integran en una misma infraestructura territorial, en la que el agua deja de ser únicamente un riesgo para convertirse en un elemento estructurante que organiza los usos, los recorridos y los ciclos productivos.',
      'A partir de esta lógica, el proyecto se construye mediante la superposición de capas. En primer lugar, la capa hidrográfica define una red de canales jerarquizados con reservorios, compuertas y bombas, garantizando el riego continuo y el funcionamiento del sistema incluso en períodos de baja disponibilidad hídrica. Sobre esta estructura se apoya la capa vial, que incorpora una nueva ruta perimetral vinculada a la Ruta Provincial 1 y a la estación ferroviaria de Viedma, asegurando la conectividad regional y el funcionamiento logístico del polo productivo.',
      'Sobre esta base infraestructural se articulan las distintas áreas de uso. La capa agroproductiva organiza los cultivos según su demanda hídrica y se vincula directamente con áreas de acopio y procesamiento, que conforman el sector productivo-industrial del sistema. Desde allí, la producción es tratada, almacenada y distribuida a través de una red logística multimodal, que articula el transporte por carretera, ferrocarril y vía fluvial, incorporando un nuevo puerto para embarcaciones de pequeño porte.',
      'En continuidad con este sistema productivo, el proyecto incorpora un área residencial rural destinada principalmente a trabajadores, implantada en relación directa con el borde costero. Este frente se consolida como un paseo público y paisajístico, integrando espacios recreativos y una reserva natural sobre sectores de vegetación preexistente, recuperando áreas del río previamente privatizadas. En las cabeceras del sistema se localizan los programas de administración y turismo, que funcionan como puntos de gestión, control y recepción de visitantes, reforzando el carácter público y territorial de la intervención.',
    ],
    description_short: 'Parque agroproductivo ubicado en Viedma (proyecto propio). Proyecto universitario para Proyecto Urbano (2025).',
    behanceUrl: 'https://www.behance.net/gallery/240786641/Parque-agroproductivo-Viedma',
    image: 'images/projects/proyecto-parque-agroproductivo/gallery/hero-09.webp',
    imageAlt: 'Parque agroproductivo',
    galleryCount: 23,
    heroImage: 'images/projects/proyecto-parque-agroproductivo/gallery/hero-09.webp',
    en: {
      title: 'Agro-productive park',
      titleAccent: 'Agro-productive park',
      titleRest: 'Viedma, Argentina',
      role: 'University project',
      tags: ['University project'],
      location: 'Viedma, Buenos Aires',
      surface: '135 km²',
      quote: "The project turns a condition of hydric vulnerability into a productive infrastructure capable of organizing the territory and building landscape.",
      description: [
        "Located on the alluvial plain of Viedma, the project responds to the flooding of the Río Negro, which recurrently affects the city due to its low elevation. While Carmen de Patagones sits on a natural bluff that protects it from flooding, Viedma sits on a vulnerable alluvial plain, where water acts simultaneously as a productive resource and a latent threat.",
        "Within this context, the proposal takes water as its starting point and lays out a canal system able to regulate and divert part of the river's flow. In this way, hydric control, agricultural production and flood mitigation are integrated into a single territorial infrastructure, in which water stops being only a risk and becomes a structuring element that organizes uses, routes and production cycles.",
        "Building on this logic, the project is constructed by overlaying layers. First, the hydrographic layer defines a hierarchical network of canals with reservoirs, gates and pumps, guaranteeing continuous irrigation and keeping the system running even in periods of low water availability. This structure supports the road layer, which adds a new perimeter route linked to Provincial Route 1 and Viedma's train station, ensuring regional connectivity and the logistics operation of the productive hub.",
        "On this infrastructural base, the different use areas are articulated. The agro-productive layer organizes crops according to their water demand and connects directly to storage and processing areas, forming the system's production-industrial sector. From there, production is treated, stored and distributed through a multimodal logistics network combining road, rail and river transport, including a new port for small vessels.",
        "In continuity with this productive system, the project incorporates a rural residential area intended mainly for workers, placed in direct relation to the coastal edge. This front is consolidated as a public, scenic promenade, integrating recreational spaces and a nature reserve over pre-existing vegetation areas, reclaiming stretches of the river that were previously privatized. Administration and tourism programs sit at the ends of the system, functioning as points of management, control and visitor reception, reinforcing the intervention's public and territorial character.",
      ],
      description_short: 'Agro-productive park located in Viedma (own project). University project for Proyecto Urbano (2025).',
      imageAlt: 'Agro-productive park',
    },
  },
  {
    id: 6,
    slug: 'proyecto-condensador-urbano',
    title: 'Centro multiprogramático',
    titleAccent: 'Centro multiprogramático',
    titleRest: 'Punta Lara, Bs. As.',
    category: 'institucional',
    academic: true,
    role: 'Proyecto universitario',
    tags: ['Proyecto universitario'],
    location: 'Punta Lara, Buenos Aires',
    year: '2024',
    surface: '47.800 m²',
    quote: 'El proyecto traza un puente entre la ruta y el río, integrando infraestructura y paisaje en un recorrido continuo que revela la profundidad del territorio.',
    description: [
      'Ubicado en Punta Lara, sobre la Ruta Provincial 11, este edificio de escala regional se implanta como un nexo entre la costanera y el canal que desemboca en el Río de la Plata. La propuesta se define por su estructura lineal, que enfatiza la relación entre arquitectura y paisaje, configurando un espacio de transición fluida entre el entorno natural y lo construido.',
      'El edificio se apoya sobre una base estructural de grandes tabiques portantes, permitiendo que los programas principales se desarrollen en un volumen suspendido, liberando la planta baja para usos públicos y reforzando la conexión visual y funcional entre la ruta y el río.',
      'La estructura del edificio se organiza en tres niveles. La planta baja, de acceso libre, alberga la estación fluvial y de micros, asegurando la movilidad de los usuarios. Un nivel intermedio funciona como piso técnico, concentrando los servicios y áreas húmedas, optimizando el funcionamiento del edificio. Finalmente, el nivel superior integra los programas públicos de grandes luces, el polideportivo y el centro cultural, que se despliegan en un nivel de acceso público, conectado por una gran rampa y pasarela exterior; y los programas privados con accesos independientes, con oficinas orientadas a la vegetación nativa y un hotel que se proyecta sobre el estuario, maximizando las visuales hacia el agua.',
      'El diseño responde al clima y la luz mediante parasoles semiabiertos, que regulan la radiación solar y la ventilación natural. Las cubiertas traslúcidas abovedadas iluminan de manera uniforme los espacios principales, mientras que en la zona de la pileta, su sistema corredizo permite una apertura total al exterior.',
      'Construido con un sistema estructural eficiente, el proyecto busca optimizar recursos y adaptarse a las condiciones del sitio, consolidándose como un referente arquitectónico y paisajístico en el borde del Río de la Plata.',
    ],
    description_short: 'Centro multiprogramático (deportes, hotel, transporte y oficinas) ubicado en Punta Lara (proyecto propio). Proyecto para Diseño IV (2024).',
    behanceUrl: 'https://www.behance.net/gallery/219425721/Condensador-urbano-Punta-Lara',
    image: 'images/projects/proyecto-condensador-urbano/gallery/hero-18.webp',
    imageAlt: 'Centro multiprogramático',
    galleryCount: 37,
    heroImage: 'images/projects/proyecto-condensador-urbano/gallery/hero-18.webp',
    en: {
      title: 'Multi-program center',
      titleAccent: 'Multi-program center',
      titleRest: 'Punta Lara, Argentina',
      role: 'University project',
      tags: ['University project'],
      location: 'Punta Lara, Buenos Aires',
      surface: '47,800 m²',
      quote: "The project draws a bridge between the highway and the river, integrating infrastructure and landscape into a continuous route that reveals the depth of the territory.",
      description: [
        'Located in Punta Lara, on Provincial Route 11, this regional-scale building sits as a link between the coastal road and the channel that flows into the Río de la Plata. The proposal is defined by its linear structure, which emphasizes the relationship between architecture and landscape, shaping a space of fluid transition between the natural surroundings and the built environment.',
        "The building rests on a structural base of large load-bearing walls, allowing the main programs to unfold in a suspended volume, freeing the ground floor for public use and reinforcing the visual and functional connection between the road and the river.",
        "The building's structure is organized into three levels. The freely accessible ground floor houses the river and bus station, ensuring user mobility. An intermediate level works as a technical floor, concentrating services and wet areas and optimizing the building's operation. Finally, the upper level integrates the large-span public programs - the sports center and cultural center, unfolding on a publicly accessible level connected by a large ramp and outdoor walkway - and the private programs with independent access, with offices facing the native vegetation and a hotel projecting over the estuary to maximize views of the water.",
        'The design responds to climate and light through semi-open sunshades that regulate solar radiation and natural ventilation. Vaulted translucent roofs evenly light the main spaces, while in the pool area a sliding system allows for full openness to the outside.',
        "Built with an efficient structural system, the project seeks to optimize resources and adapt to the site's conditions, establishing itself as an architectural and landscape landmark on the edge of the Río de la Plata.",
      ],
      description_short: 'Multi-program center (sports, hotel, transport and offices) located in Punta Lara (own project). Project for Diseño IV (2024).',
      imageAlt: 'Multi-program center',
    },
  },
  {
    id: 5,
    slug: 'proyecto-centro-integral',
    title: 'Centro integral',
    titleAccent: 'Centro integral',
    titleRest: 'Isla Martín García, Arg.',
    category: 'institucional',
    academic: true,
    role: 'Proyecto universitario',
    tags: ['Proyecto universitario'],
    location: 'Isla Martín García, Río de la Plata',
    year: '2024',
    surface: '9.480 m²',
    quote: 'El diseño se extiende en una línea continua, invitando a los usuarios a recorrer cada espacio en un flujo ininterrumpido que resalta la conexión con el entorno.',
    description: [
      'Esta obra, realizada para Diseño IV en 2024, está ubicada sobre un pequeño golfo natural en la Isla Martín García. El proyecto se destaca por su estructura lineal que enfatiza la horizontalidad y la simplicidad en su forma. La construcción, apoyada en tierra y agua, se integra con la topografía, ofreciendo diferentes perspectivas según el punto de vista del usuario. Desde la Isla Timoteo Domínguez, el edificio se destaca en el horizonte, mientras que desde el casco histórico de la Isla Martín García, pasa casi desapercibido debido a su baja pendiente.',
      'La estructura triangular define la forma del edificio y abarca tres niveles. Los programas públicos están situados en los pisos inferiores, aprovechando la mayor superficie disponible gracias al ensanchamiento del triángulo. Los espacios privados se encuentran en los niveles superiores, optimizando el uso del espacio vertical. El ágora, que requiere tanto superficie como altura, se extiende a lo largo de los tres niveles de manera flexible, maximizando el espacio disponible.',
      'El edificio cuenta con cerramientos de policarbonato traslúcido y ventanas plegables, que permiten una abundante entrada de luz y ventilación natural. Esta elección contribuye a una experiencia sensorial enriquecedora, al interactuar con el paisaje acuático y natural circundante.',
      'Diseñado con una estructura modular de madera, el proyecto se integra armoniosamente con el entorno, facilitando la construcción en un lugar de difícil acceso y destacando por su capacidad de adaptarse a las condiciones específicas del sitio. Esta solución no solo mejora la sostenibilidad del proyecto, sino que también resalta su diseño innovador y su integración con el paisaje.',
    ],
    description_short: 'Centro integral de ciencia y recreación ubicado en la Isla Martín García (proyecto propio). Proyecto para Diseño IV (2024).',
    behanceUrl: 'https://www.behance.net/gallery/206097727/Centro-integral-Isla-Martin-Garcia',
    image: 'images/projects/proyecto-centro-integral/gallery/hero-17.webp',
    imageAlt: 'Centro integral',
    galleryCount: 36,
    heroImage: 'images/projects/proyecto-centro-integral/gallery/hero-17.webp',
    en: {
      title: 'Science & recreation center',
      titleAccent: 'Science & recreation center',
      titleRest: 'Martín García Island, Argentina',
      role: 'University project',
      tags: ['University project'],
      location: 'Martín García Island, Río de la Plata',
      surface: '9,480 m²',
      quote: "The design extends in a continuous line, inviting users to move through each space in an uninterrupted flow that highlights the connection with its surroundings.",
      description: [
        "This project, developed for Diseño IV in 2024, sits on a small natural inlet on Martín García Island. It stands out for its linear structure, which emphasizes horizontality and formal simplicity. Resting on both land and water, the building integrates with the topography, offering different perspectives depending on the viewer's vantage point. Seen from Timoteo Domínguez Island, the building stands out on the horizon, while from Martín García's historic quarter it goes almost unnoticed thanks to its low profile.",
        'A triangular structure defines the building’s form across three levels. Public programs sit on the lower floors, taking advantage of the greater surface available as the triangle widens. Private spaces occupy the upper levels, optimizing the use of vertical space. The agora, which needs both floor area and height, extends flexibly across all three levels, maximizing available space.',
        'The building features translucent polycarbonate enclosures and folding windows that allow abundant natural light and ventilation. This choice contributes to an enriching sensory experience, engaging with the surrounding aquatic and natural landscape.',
        "Designed with a modular timber structure, the project blends harmoniously with its surroundings, easing construction in a hard-to-access location and standing out for its ability to adapt to the site's specific conditions. This solution not only improves the project's sustainability but also highlights its innovative design and integration with the landscape.",
      ],
      description_short: 'Science and recreation center located on Martín García Island (own project). Project for Diseño IV (2024).',
      imageAlt: 'Science and recreation center',
    },
  },
  {
    id: 4,
    slug: 'proyecto-diseño-ph',
    title: 'Diseño de interiores PH',
    titleAccent: 'Diseño de interiores PH',
    titleRest: 'Villa Crespo, CABA',
    category: 'residencial',
    academic: false,
    role: 'Proyecto y contacto con proveedores',
    tags: ['Proyecto y contacto con proveedores'],
    location: 'Villa Crespo, CABA',
    year: '2024',
    surface: '145 m²',
    quote: 'No solo se trata de diseño, sino también de preservar la esencia del lugar.',
    description: [
      'Este proyecto de diseño de interiores para un PH en Villa Crespo se enfoca en resaltar la belleza y carácter de la obra original, manteniendo sus pisos y paredes para conservar su historia. Cada detalle de este espacio ha sido cuidadosamente considerado para lograr una fusión armoniosa entre lo ya existente y lo contemporáneo. La paleta de colores neutros, con tonos blancos, negros y marrones, se combina con toques de madera natural para crear un ambiente luminoso y cálido que invita a la tranquilidad.',
      'El objetivo principal es crear un hogar que no solo sea funcional y cómodo, sino que también cuente una historia a través de sus elementos arquitectónicos originales, evitando también generar grandes costos para su realización.',
    ],
    description_short: 'Diseño de interiores para PH ubicado en Villa Crespo, CABA (proyecto propio). Proyecto y contacto con proveedores (2024).',
    behanceUrl: 'https://www.behance.net/gallery/196214019/Diseno-Interiores-PH-%28CABA%29',
    image: 'images/projects/proyecto-diseño-ph/preview.jpg',
    imageAlt: 'Diseño de interiores PH',
    galleryCount: 10,
    heroIndex: 2,
    en: {
      title: 'PH interior design',
      titleAccent: 'PH interior design',
      titleRest: 'Villa Crespo, Buenos Aires',
      role: 'Design & supplier coordination',
      tags: ['Design & supplier coordination'],
      location: 'Villa Crespo, Buenos Aires',
      surface: '145 m²',
      quote: "It isn't only about design - it's also about preserving the essence of the place.",
      description: [
        'This interior design project for a PH (row house) in Villa Crespo focuses on highlighting the beauty and character of the original construction, keeping its floors and walls to preserve its history. Every detail of this space was carefully considered to achieve a harmonious fusion between what already existed and the contemporary. A neutral color palette of whites, blacks and browns combines with touches of natural wood to create a bright, warm atmosphere that invites calm.',
        'The main goal is to create a home that is not only functional and comfortable, but also tells a story through its original architectural elements - all while keeping costs down.',
      ],
      description_short: 'Interior design for a PH in Villa Crespo, Buenos Aires (own project). Design and supplier coordination (2024).',
      imageAlt: 'PH interior design',
    },
  },
  {
    id: 3,
    slug: 'proyecto-bodega',
    title: 'Complejo enológico',
    titleAccent: 'Complejo enológico',
    titleRest: 'Cafayate, Salta',
    category: 'institucional',
    academic: true,
    role: 'Proyecto universitario',
    tags: ['Proyecto universitario'],
    location: 'Cafayate, Salta',
    year: '2023',
    surface: '6.400 m²',
    quote: 'Donde la arquitectura se encuentra con la naturaleza: una bodega diseñada para integrarse con el paisaje y ofrecer una experiencia inmersiva en la producción y degustación del vino.',
    description: [
      'Este proyecto, realizado en 2023 para Diseño III, presenta una bodega integrada en la topografía de Cafayate. Al inicio del recorrido, se encuentra un estacionamiento con un puesto de bicicletas, donde los visitantes pueden dejar su vehículo y decidir si continuar el recorrido pedaleando o a pie. En la parte más alta del recorrido, se ubica un mirador, que aprovecha su altura para ofrecer impresionantes vistas y culmina la caminata.',
      'La bodega está ubicada en el medio de ambos. En la planta de acceso, se encuentra una zona de descanso con pérgolas para proteger a los visitantes del sol, además de un restaurante, una administración y el hall de entrada. El área de producción del vino se ubica en los niveles inferiores, dividiéndose en tres sectores principales. Estos espacios se distribuyen en forma de peine, y se conectan visualmente con el entorno mediante dos patios que se integran con la montaña.',
      'Esta disposición facilita un flujo continuo en la producción, ya que se conforma de manera cíclica, permitiendo que camiones lleguen y salgan por el mismo sector, sin interrumpir la experiencia de los visitantes. El recorrido de los usuarios, a su vez, está diseñado para observar el proceso de producción sin interferir con las operaciones, finalizando en una sala de cata con vista a las barricas.',
      'Se escogió una estructura de acero para permitir grandes luces, brindándole a la producción amplios espacios sin columnas intermedias. Para los cerramientos se diseñaron gaviones rellenos de piedra local, para fundirse con el paisaje natural de Cafayate y generar un control climático óptimo para la crianza del vino.',
    ],
    description_short: 'Bodega implantada sobre la montaña, ubicada en Cafayate, Salta (proyecto propio). Proyecto para Diseño III (2023).',
    behanceUrl: 'https://www.behance.net/gallery/192672761/Bodega-Cafayate-Salta',
    image: 'images/projects/proyecto-bodega/gallery/11.webp',
    imageAlt: 'Complejo enológico',
    galleryCount: 25,
    heroIndex: 11,
    en: {
      title: 'Winery complex',
      titleAccent: 'Winery complex',
      titleRest: 'Cafayate, Argentina',
      role: 'University project',
      tags: ['University project'],
      location: 'Cafayate, Salta',
      surface: '6,400 m²',
      quote: "Where architecture meets nature: a winery designed to blend into the landscape and offer an immersive experience of wine production and tasting.",
      description: [
        'This project, developed in 2023 for Diseño III, presents a winery embedded in the topography of Cafayate. At the start of the route sits a parking area with a bike rack, where visitors can leave their vehicle and choose to continue on foot or by bicycle. At the highest point of the route, a lookout takes advantage of its elevation to offer sweeping views and close out the walk.',
        'The winery sits between the two. On the entry level, a rest area with pergolas shelters visitors from the sun, alongside a restaurant, administration offices and the entrance hall. The wine production area occupies the lower levels, split into three main sectors. These spaces are arranged in a comb pattern and connect visually to the surroundings through two courtyards that merge with the mountain.',
        'This layout allows for a continuous production flow, organized cyclically so trucks can arrive and leave through the same sector without interrupting the visitor experience. The visitor route, in turn, is designed to observe the production process without interfering with operations, ending in a tasting room overlooking the barrels.',
        "A steel structure was chosen to allow for long spans, giving the production area ample column-free space. The enclosures were designed as gabions filled with local stone, blending into Cafayate's natural landscape and providing optimal climate control for aging the wine.",
      ],
      description_short: 'Winery built into the mountainside in Cafayate, Salta (own project). Project for Diseño III (2023).',
      imageAlt: 'Winery complex',
    },
  },
  {
    id: 2,
    slug: 'proyecto-hotel-museo',
    title: 'Complejo hotelero y cultural',
    titleAccent: 'Complejo hotelero y cultural',
    titleRest: 'Cafayate, Salta',
    category: 'institucional',
    academic: true,
    role: 'Proyecto universitario',
    tags: ['Proyecto universitario'],
    location: 'Cafayate, Salta',
    year: '2023',
    surface: '6.400 m²',
    quote: 'La arquitectura se posa sobre la montaña sin imponerse, utilizando la piedra y el paisaje como materia principal del proyecto.',
    description: [
      'Este proyecto, realizado en 2023 para Diseño III, se ubica en las montañas de Cafayate y propone un hotel integrado al paisaje, evitando competir con el entorno natural y buscando una relación respetuosa con la topografía existente. La implantación aprovecha el desnivel del terreno para organizar los distintos programas del edificio, permitiendo que la arquitectura se adapte a la montaña y establezca una relación permanente con las visuales del valle.',
      'Comprendiendo las dificultades constructivas propias del sitio, se optó por una estructura liviana y modular de perfiles de acero, facilitando el transporte y el montaje en un contexto de difícil acceso. Sin embargo, hacia el exterior, la arquitectura expresa una imagen de solidez y permanencia mediante una materialidad pétrea, utilizando revestimientos de piedra autóctona que permiten que el edificio se funda visualmente con el paisaje. Los muros que nacen de la montaña también se resuelven íntegramente con piedra natural, reforzando la sensación de arraigo al terreno y generando una experiencia inmersiva en contacto con el entorno.',
      'El acceso al complejo se produce desde una nueva ruta que alcanza el segundo nivel del edificio mediante un sistema de rampas y escaleras. Allí se desarrolla el ingreso principal y el museo de doble altura, concebido para albergar esculturas de gran escala de Gabriel Chaile, cuya dimensión aprovecha la espacialidad del recinto. En el nivel superior continúa el recorrido museográfico mediante exposiciones de artistas locales, organizadas alrededor de un balcón interior que permite observar las esculturas del nivel inferior. Este sector incorpora además un pequeño auditorio y una sala de reuniones destinados a actividades culturales y eventos.',
      'Las áreas públicas del hotel se distribuyen en distintos niveles. La planta baja y el primer piso albergan el restaurante, cuyos espacios se abren hacia el paisaje montañoso mediante amplias superficies vidriadas que convierten la experiencia gastronómica en una extensión del entorno natural. En el nivel de ingreso se ubican además las oficinas administrativas, una piscina exterior vidriada con vistas panorámicas y tres glampings independientes que ofrecen una experiencia de alojamiento vinculada directamente con la montaña. El cuarto nivel concentra las áreas de bienestar del hotel, incorporando gimnasio, spa y dos piscinas orientadas hacia las visuales privilegiadas del valle.',
      'Los niveles superiores albergan las habitaciones y las unidades de alojamiento de mayor permanencia, incorporando departamentos equipados con cocina y espacios ampliados. De esta manera, el proyecto combina hotelería, cultura y paisaje en una arquitectura que se integra al territorio y convierte la experiencia de la montaña en el principal protagonista del edificio.',
    ],
    description_short: 'Hotel con exposiciones de artista local, ubicado en Cafayate, Salta (proyecto propio). Proyecto para Diseño III (2023).',
    behanceUrl: 'https://www.behance.net/gallery/192670781/Hotel-Museo-Cafayate-Salta',
    image: 'images/projects/proyecto-hotel-museo/preview.jpg',
    imageAlt: 'Complejo hotelero y cultural',
    galleryCount: 25,
    heroIndex: 4,
    en: {
      title: 'Hotel & cultural complex',
      titleAccent: 'Hotel & cultural complex',
      titleRest: 'Cafayate, Argentina',
      role: 'University project',
      tags: ['University project'],
      location: 'Cafayate, Salta',
      surface: '6,400 m²',
      quote: "The architecture rests on the mountain without imposing itself, using stone and landscape as the project's core material.",
      description: [
        "This project, developed in 2023 for Diseño III, is located in the mountains of Cafayate and proposes a hotel integrated into the landscape, avoiding competition with its natural surroundings and seeking a respectful relationship with the existing topography. The siting takes advantage of the site's slope to organize the building's different programs, letting the architecture adapt to the mountain and establish a lasting relationship with the valley views.",
        "Understanding the site's construction challenges, a lightweight, modular steel-frame structure was chosen to ease transport and assembly in a hard-to-access context. On the outside, however, the architecture projects an image of solidity and permanence through a stone-based materiality, using local stone cladding that lets the building visually merge with the landscape. The walls that emerge from the mountain are also fully finished in natural stone, reinforcing the sense of rootedness in the terrain and creating an immersive experience in contact with the surroundings.",
        "Access to the complex comes from a new route that reaches the building's second level via a system of ramps and stairs. There, the main entrance and a double-height museum unfold, conceived to house large-scale sculptures by Gabriel Chaile, whose scale takes full advantage of the room's spatiality. On the upper level, the museum route continues through exhibitions by local artists, arranged around an interior balcony overlooking the sculptures below. This sector also includes a small auditorium and a meeting room for cultural activities and events.",
        "The hotel's public areas are spread across different levels. The ground floor and first floor house the restaurant, whose spaces open toward the mountain landscape through large glazed surfaces that turn the dining experience into an extension of the natural surroundings. The entrance level also holds the administrative offices, a glazed outdoor pool with panoramic views, and three independent glamping units offering an accommodation experience directly connected to the mountain. The fourth level concentrates the hotel's wellness areas, with a gym, spa and two pools facing the valley's best views.",
        'The upper levels house the guest rooms and longer-stay accommodation units, including apartments equipped with a kitchen and larger living spaces. In this way, the project combines hospitality, culture and landscape in an architecture that integrates with the territory and makes the mountain experience the building’s main protagonist.',
      ],
      description_short: 'Hotel featuring exhibitions by a local artist, located in Cafayate, Salta (own project). Project for Diseño III (2023).',
      imageAlt: 'Hotel and cultural complex',
    },
  },
  {
    id: 1,
    slug: 'proyecto-el-oasis',
    title: 'Edificio residencial Oasis urbano',
    titleAccent: 'Edificio residencial Oasis urbano',
    titleRest: 'Montserrat, CABA',
    category: 'residencial',
    academic: true,
    role: 'Proyecto universitario',
    tags: ['Proyecto universitario'],
    location: 'Montserrat, CABA',
    year: '2022',
    surface: '10.100 m²',
    quote: 'Un oasis dentro de la ciudad, donde la arquitectura, el paisaje y la comunidad se integran para construir nuevas formas de habitar el entorno urbano.',
    description: [
      'Este proyecto, realizado en 2022 para Diseño II, se ubica en el barrio de Monserrat, en la Ciudad Autónoma de Buenos Aires, y propone una nueva forma de habitar la ciudad a través de la incorporación de espacios verdes, ámbitos colectivos y programas de uso mixto. Frente a la densidad edilicia característica del sector, la propuesta busca generar un respiro urbano que mejore la calidad ambiental y recupere espacios de encuentro y permanencia para los habitantes del barrio.',
      'La implantación se resuelve mediante dos volúmenes que respetan las alturas de las construcciones linderas y se separan para conformar un vacío central de menor escala. Este espacio intermedio favorece la ventilación e iluminación natural del conjunto, al tiempo que disminuye la sensación de densidad propia de la manzana. La morfología orgánica del edificio rompe con la rigidez de la trama urbana existente y amplía las superficies de circulación peatonal mediante el ensanchamiento de las veredas, otorgándole parte del terreno a la ciudad y consolidando una nueva identidad para la esquina.',
      'Los niveles públicos del proyecto se desarrollan en la planta baja y el subsuelo, donde se propone un programa gastronómico acompañado por espacios de permanencia y áreas verdes. La incorporación de distintas especies arbóreas y vegetales genera recorridos con diferentes colores, aromas y texturas, construyendo diversas atmósferas a lo largo del edificio. Más allá de funcionar como un patio gastronómico, estos espacios buscan convertirse en un lugar de encuentro para los vecinos y en una extensión del espacio público del barrio.',
      'Los usos colectivos continúan en los niveles intermedios mediante oficinas, espacios de coworking y áreas comunes destinadas al estudio y al trabajo. Estas funciones promueven nuevas formas de interacción entre los usuarios y fortalecen el carácter comunitario del conjunto, entendiendo al edificio como un soporte para la vida urbana y las actividades compartidas.',
      'Las viviendas se desarrollan a partir de los niveles superiores, donde cada unidad cuenta con amplios balcones que funcionan como extensiones privadas del espacio habitable y favorecen la relación con el exterior. La disposición escalonada de los volúmenes y las formas curvas permiten generar terrazas accesibles y espacios verdes elevados destinados al descanso, la contemplación y la recreación.',
      'Las cubiertas incorporan además propuestas de huerta urbana y sectores de vegetación que buscan fortalecer el vínculo entre los habitantes y el medioambiente. De esta manera, el proyecto integra vivienda, trabajo y espacio público en una arquitectura que transforma la naturaleza en el principal elemento articulador de la experiencia urbana.',
    ],
    description_short: 'Edificio de locales, oficinas y viviendas, ubicado en Montserrat (proyecto propio). Proyecto para Diseño II (2022).',
    behanceUrl: 'https://www.behance.net/gallery/158943687/Edificio-El-Oasis-Montserrat',
    image: 'images/projects/proyecto-el-oasis/gallery/hero-13.webp',
    imageAlt: 'Edificio residencial Oasis urbano',
    galleryCount: 37,
    heroImage: 'images/projects/proyecto-el-oasis/gallery/hero-13.webp',
    en: {
      title: 'Oasis Urbano residential building',
      titleAccent: 'Oasis Urbano residential building',
      titleRest: 'Montserrat, Buenos Aires',
      role: 'University project',
      tags: ['University project'],
      location: 'Montserrat, Buenos Aires',
      surface: '10,100 m²',
      quote: "An oasis within the city, where architecture, landscape and community come together to build new ways of inhabiting the urban environment.",
      description: [
        "This project, developed in 2022 for Diseño II, is located in the Monserrat neighborhood of the City of Buenos Aires and proposes a new way of inhabiting the city through green spaces, collective areas and mixed-use programs. Facing the block's characteristic building density, the proposal seeks to create an urban breathing room that improves environmental quality and restores gathering and lingering spaces for the neighborhood's residents.",
        "The siting is resolved through two volumes that respect the height of the neighboring buildings and pull apart to form a smaller-scale central void. This intermediate space favors the complex's natural ventilation and lighting while reducing the sense of density typical of the block. The building's organic form breaks with the rigidity of the existing urban grid and widens pedestrian circulation by expanding the sidewalks, giving part of the site back to the city and consolidating a new identity for the corner.",
        "The project's public levels unfold on the ground floor and basement, where a food-and-beverage program is proposed alongside lingering areas and green spaces. The addition of different tree and plant species creates routes with varying colors, scents and textures, building distinct atmospheres throughout the building. Beyond functioning as a food court, these spaces aim to become a gathering place for neighbors and an extension of the neighborhood's public space.",
        'Collective uses continue on the intermediate levels through offices, coworking spaces and common areas for study and work. These functions promote new forms of interaction between users and strengthen the complex’s community character, treating the building as a support structure for urban life and shared activities.',
        'The housing units unfold from the upper levels, where each one has large balconies that act as private extensions of the living space and encourage a relationship with the exterior. The staggered arrangement of the volumes and their curved forms allow for accessible terraces and elevated green spaces intended for rest, contemplation and recreation.',
        'The roofs also incorporate urban garden proposals and vegetated sectors that aim to strengthen the bond between residents and the environment. In this way, the project integrates housing, work and public space into an architecture that makes nature the main structuring element of the urban experience.',
      ],
      description_short: 'Building with retail, offices and housing, located in Montserrat, Buenos Aires (own project). Project for Diseño II (2022).',
      imageAlt: 'Oasis Urbano residential building',
    },
  },
];

// Exportar para uso en módulos (Node.js / bundlers)
if (typeof module !== 'undefined') { module.exports = projects; }
